# Generated by Django 4.1.3 on 2022-12-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
